M48
; DRILL file {KiCad 7.0.7} date Sun Sep 24 19:30:15 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-09-24T19:30:15+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C1.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C3.000
%
G90
G05
T1
X154.985Y-45.497
X159.985Y-45.497
T2
X138.399Y-81.718
T3
X138.399Y-102.718
T4
X104.13Y-87.979
X104.14Y-49.183
X172.136Y-49.193
T0
M30
